# Settings in the [build] context are global and are applied to
# all contexts unless otherwise overridden by more specific contexts.
[build]
  ignore = "npx turbo-ignore"
  publish = "./apps/web/.next/"
  command = "npx turbo run build --filter='web'"

[functions]
  included_files = [

    "!../../node_modules/sharp/vendor/*",

    "!../../node_modules/@esbuild/*",

    "!../../node_modules/@esbuild/*",

    "!../../node_modules/@swc/core-linux-x64-musl/*",

    "!../../node_modules/@swc/core-linux-x64-gnu/*",

    "!../../node_modules/@swc/core-darwin-x64/*",

    "!../../node_modules/sharp/vendor/8.14.5/linux-x64/lib/libvips-cpp.so.42",

    "!../../node_modules/@esbuild/linux-x64/bin/esbuild",

    "!../../node_modules/esbuild/lib/downloaded-@esbuild-linux-x64-esbuild",

    "!../../node_modules/esbuild/lib/downloaded-@esbuild-linux-x64-esbuild",

    "!../../node_modules/@fortawesome/pro-regular-svg-icons/index.js",

    "!../../node_modules/@fortawesome/pro-solid-svg-icons/index.js",

  ]

[[redirects]]
  force = true
  from = "/munchkin.js"
  status = 200
  to = "https://862-jiq-698.mktoweb.com/munchkin.js"

[[redirects]]
  force = true
  from = "/uc.js"
  status = 200
  to = "https://consent.cookiebot.com/uc.js"

[[redirects]]
  force = true
  from = "/heap.js"
  status = 200
  to = "https://cdn.heapanalytics.com/js/heap-4050918174.js"

[[redirects]]
  force = true
  from = "/uwt.js"
  status = 200
  to = "https://static.ads-twitter.com/uwt.js"

[[edge_functions]]
  function = "add-slash"
  path = "/*"

[[plugins]]
  package = "@netlify/plugin-nextjs"
